services:
  otel-collector:
    image: otel/opentelemetry-collector-dev:latest
    ports:
      - "4317:4317"

  valkey:
    image: valkey/valkey:8.1-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d:r
    command: postgres -c log_statement=all
